version: "3.3"

services:
  web:
    image: my-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      REACT_APP_SERVER_URL: /api

  backend:
    image: my-go-server
    ports:
      - "8080"
    depends_on:
      - db
    environment:
      - DBURL=db
      - DBPASSWORD=example

  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example

